# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
  
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: false
    goals: 'package'
- stage: Policy
  jobs:
  - job: evaluate
    container: sonatype/gitlab-nexus-iq-pipeline:1.1 
    steps:
    - script: /sonatype/evaluate -i A1 -a admin:admin123 $(Build.StagingDirectory)
    
